### ISSUE TITLE
Add more rigorous checks to storage key input / consider a simpler auth model

### ISSUE THREAD

**Issue by gauntface** [googleapis/google-cloud-node#2825]
#### Environment details

  - OS: Linux
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - google-cloud-node version: "@google-cloud/storage": "^1.7.0"

#### Steps to reproduce

I was getting this error when using the `private_key` to authenticate with google cloud storage.

```
Service initialization error: error:0906D06C:PEM routines:PEM_read_bio:no startline
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:307:26)
    at Object.sign (/opt/ghcrawler/node_modules/jwa/index.js:76:45)
    at Object.jwsSign [as sign] (/opt/ghcrawler/node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.<anonymous> (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:250:33)
    at step (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:42:23)
    at Object.next (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:23:53)
    at /opt/ghcrawler/node_modules/gtoken/build/src/index.js:17:71
    at __awaiter (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:13:12)
    at GoogleToken.requestToken (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:236:16)
    at GoogleToken.<anonymous> (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:176:56)
    at step (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:42:23)
    at Object.next (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:23:53)
    at /opt/ghcrawler/node_modules/gtoken/build/src/index.js:17:71
    at __awaiter (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:13:12)
    at GoogleToken.getTokenAsync (/opt/ghcrawler/node_modules/gtoken/build/src/index.js:155:16)
```

I am using environment variables to get this value through and have tried replacing the string '\n' (which is really '\\n' with the new line character, but that still throws the same error.

In a 2015 bug there was a statement saying there was more rigorous checking being performed on the input, but give a range of different inputs, I get the above error with no guidance.

In the end my input was being quoted via the environment variable, but the way to figure this out was manually copying and pasting different values to get different errors.

A valid key but email of "XXX@XXXX.com" was throwing the error:

```
Error:invalid_Client The OAuth client was not found
```

Neither of these error messages are helpful to figure out the end problem and having to provide multiple entries with little guidance in terms of *where* to get there values, it would be incredibly helpful if:

1. The error checking for these types were better (i.e. this doesn't look like an email we'd use) or this key doesn't start with `----BEGIN PRIVATE KEY----\n` etc
1. Move to a single value and give that value up front instead of picking apart out of a JSON file.

**Comment by JustinBeckwith** [comment]
Greetings!  I'd love to hear more.  What environment variable specifically are you trying to set? Can you share the code you're using?

**Comment by gauntface** [comment]
The environment variable is specific to my code,

Code ultimately boils down to:

```
   const storageDetails = {
      projectId: process.env.PROJECT_ID,
      credentials: {
        client_email: process.env.CLIENT_EMAIL,
        private_key: process.env.PRIVATE_KEY.replace(/\\n/g, '\n'),
      }
    };
    this.storage = new Storage(storageDetails);
```

**Comment by zmknox** [comment]
I'm getting a very similar error when running `bucket.uploadFile()`,

- OS: macOS 10.13.6
- Node.js version: v10.16.0
- nom version: v6.9.0
- google-cloud-node version: "@google-cloud/storage": "2.5.0"

```Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:80:26)
    at Object.sign (/Users/zknox/Development/testaggregator-api/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/Users/zknox/Development/testaggregator-api/node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.<anonymous> (/Users/zknox/Development/testaggregator-api/node_modules/@google-cloud/common/node_modules/gtoken/build/src/index.js:190:35)
    at Generator.next (<anonymous>)
    at /Users/zknox/Development/testaggregator-api/node_modules/@google-cloud/common/node_modules/gtoken/build/src/index.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/zknox/Development/testaggregator-api/node_modules/@google-cloud/common/node_modules/gtoken/build/src/index.js:9:12)
    at GoogleToken.requestToken (/Users/zknox/Development/testaggregator-api/node_modules/@google-cloud/common/node_modules/gtoken/build/src/index.js:179:16)
    at GoogleToken.<anonymous> (/Users/zknox/Development/testaggregator-api/node_modules/@google-cloud/common/node_modules/gtoken/build/src/index.js:125:25)```

The storage object is given a project id and credentials (client email, private key) via a StorageOptions object (pulled from HashiCorp Vault through a separate system, but that shouldn't be relevant), and I'm almost certain that the account given is valid, but it still seems to fail.

**Comment by bcoe** [comment]
closing as stale, please let us know if you're continuing to run into any issues.
