### ISSUE TITLE
createBucket results in incorrect Metadata-Flavor

### ISSUE THREAD

**Issue by Connorelsea** [googleapis/google-cloud-node#2885]
I included @google-cloud/storage in my node project and am attempting to do a basic creation of a bucket, but the function just results in an error everytime, the Metadata-Flavor error listed below. I attempted to manually add this header to every request leaving my node server, but that didn't work, and I didn't see that anywhere in the guide so I'm really not sure where I went wrong.

#### Environment details

  - OS: macOS 10.14
  - Node.js version: 9.8.0
  - yarn version: 1.12.3
  - google-cloud-node version: 2.3.1

#### Steps to reproduce

  1. require `@google-cloud/storage`
  2. attempt to use basic createBucket functions
  3. get Metadata-Flavor error

![image](https://user-images.githubusercontent.com/1844458/48928010-a5e18b00-eea0-11e8-846c-3b93bcdd6a52.png)

I get this error

`
Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at GoogleAuth.<anonymous> (/Users/connorelsea/Projects/remix-server/node_modules/google-auth-library/build/src/auth/googleauth.js:163:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/connorelsea/Projects/remix-server/node_modules/google-auth-library/build/src/auth/googleauth.js:20:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:20467) UnhandledPromiseRejectionWarning: Error: Unexpected error determining execution environment: Invalid response from metadata service: incorrect Metadata-Flavor header.
    at GoogleAuth.<anonymous> (/Users/connorelsea/Projects/remix-server/node_modules/google-auth-library/build/src/auth/googleauth.js:163:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/connorelsea/Projects/remix-server/node_modules/google-auth-library/build/src/auth/googleauth.js:20:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
`

**Comment by mattferrin** [comment]
Started receiving error. Maybe something changed when the service account JSON key file was mistakenly moved? I re-exported the GOOGLE_APPLICATION_CREDENTIALS environment variable. Then I generated a new key and gave it an admin role on the relevant S3 object. Still can't write image to bucket.
