### ISSUE TITLE
No Instructions on How to Run Samples Tests

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloud-node#2935]
There should be instructions on how to run the samples tests for this repo:

```sh
npm run samples-test
```

```
  Cloud Task Sample Tests
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    1) should create a queue
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    2) should create a task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    3) quickstart sample should create a task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    4) should create a HTTP task
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    5) should create a HTTP task with token
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/Users/timmerman/Documents/github/googleapis/nodejs-tasks/node_modules/google-auth-library/build/src/auth/googleauth.js:162:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
    6) should delete a queue


  0 passing (3s)
  6 failing
```

Setting up a service account env var didn't seem to work either.

```sh
export GOOGLE_APPLICATION_CREDENTIALS="service_account_location.json"
npm run samples-test
```

Same result. (The Cloud Tasks API is enabled)

---

What am I doing wrong? Ideally I can run these samples or run the tests without much trouble.

**Comment by grant** [comment]
A recent run was pretty good, but there is likely setup required that I am missing:

```
 npm test

> appengine-cloudtasks@ test /Users/timmerman/Documents/github/googleapis/nodejs-tasks/samples
> mocha



  Cloud Task Sample Tests
    ✓ should create a queue (1687ms)
    ✓ should create a task (1728ms)
    ✓ quickstart sample should create a task (1869ms)
    ✓ should create a HTTP task (1979ms)
7 PERMISSION_DENIED: The principal (user or service account) lacks IAM permission "iam.serviceAccounts.actAs" for the resource "test-run-invoker@long-door-651.iam.gserviceaccount.com" (or the resource may not exist).
    1) should create a HTTP task with token
    ✓ should delete a queue (1884ms)


  5 passing (12s)
  1 failing

  1) Cloud Task Sample Tests
       should create a HTTP task with token:
     Error: Command failed: node createHttpTaskWithToken serverless-com-demo my-queue us-central1 https://example.com/taskhandler test-run-invoker@long-door-651.iam.gserviceaccount.com
7 PERMISSION_DENIED: The principal (user or service account) lacks IAM permission "iam.serviceAccounts.actAs" for the resource "test-run-invoker@long-door-651.iam.gserviceaccount.com" (or the resource may not exist).

      at checkExecSyncError (child_process.js:616:11)
      at execSync (child_process.js:652:15)
      at exec (test/test.samples.js:23:21)
      at Context.<anonymous> (test/test.samples.js:65:20)
      at processImmediate (internal/timers.js:458:21)



npm ERR! Test failed.  See above for more details.
```

**Comment by meredithslota** [comment]
Most (all?) samples have been migrated to their respective individual repos, so I think this issue is obsolete (e.g. see https://github.com/googleapis/nodejs-tasks/blob/main/samples/test/test.samples.js for testing Task samples).
