### ISSUE TITLE
Should uploading not use async internally instead of sync?

### ISSUE THREAD

**Issue by Christilut** [googleapis/google-cloud-node#2963]
I just ran my nodejs express server with the ` --trace-sync-io` flag that prints synchronous calls and I see tons of these when uploading a file through Firebase Storage:
```
(node:10320) WARNING: Detected use of sync API
    at openSync (fs.js:437:26)
    at readFileSync (fs.js:342:35)
    at get all (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:34:25)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:81:23)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:352:26)
    at onChunk (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:237:22)
    at Transform._read (_stream_transform.js:189:10)
    at Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
(node:10320) WARNING: Detected use of sync API
    at tryStatSync (fs.js:304:25)
    at readFileSync (fs.js:344:17)
    at get all (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:34:25)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:81:23)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:352:26)
    at onChunk (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:237:22)
    at Transform._read (_stream_transform.js:189:10)
    at Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
```

Should these calls not be async instead? Is there a reason that they are all sync?

**Comment by stephenplusplus** [comment]
This is a library we are using called "configstore": https://github.com/yeoman/configstore/blob/764ac63d17de9e3d322c1c42180a8d5bec85391a/index.js#L34. Their reasoning for the sync usage is mentioned in this issue: https://github.com/yeoman/configstore/issues/20

**Comment by Christilut** [comment]
Well okay but how does this impact performance? Has there been a comparison between sync and async usage in google-cloud-node? When I said that I see tons of those sync warnings I really mean in the hundreds to thousands, for a very short uncomplicated request.

I don't know what the primary intended usage of configstore is, but you can expect google-cloud-node to be used in server applications that should be non-blocking. 

If there is a performance hit then usage of configstore should be reconsidered. And looking at what configstore does, it doesn't seem so complex to create a more suitable solution for this that's async.

**Comment by stephenplusplus** [comment]
Yeah, let’s talk it out and do some tests. Why hundreds to thousands for a simple request, though? Can you show that repro code? I believe we should only be calling it 1-2 times at the start of an upload.
