### ISSUE TITLE
cloud-rad publication script has been failing for some time

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-cloud-node#3502]
Some of the issues with the script have been fixed, but there's an ongoing problem with CloudRad's CLI not working in the mono-repo structure, see:

```bash
Checking out .
fatal: Not a git repository (or any parent up to mount point /h)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error: Command failed: /workspace/.kokoro/release/docs-devsite-single.sh
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at /h/.npm/_npx/9/lib/node_modules/@[google-cloud/mono-repo-publish/build/src/main.js:167](https://cs.corp.google.com/piper///depot/google3/google-cloud/mono-repo-publish/build/src/main.js?l=167):25
    at eachSubmodule (/h/.npm/_npx/9/lib/node_modules/@[google-cloud/mono-repo-publish/build/src/main.js:107](https://cs.corp.google.com/piper///depot/google3/google-cloud/mono-repo-publish/build/src/main.js?l=107):29)
    at Object.publishCustom (/h/.npm/_npx/9/lib/node_modules/@[google-cloud/mono-repo-publish/build/src/main.js:164](https://cs.corp.google.com/piper///depot/google3/google-cloud/mono-repo-publish/build/src/main.js?l=164):20)
    at Object.handler (/h/.npm/_npx/9/lib/node_modules/@[google-cloud/mono-repo-publish/build/src/bin/mono-repo-publish.js:123](https://cs.corp.google.com/piper///depot/google3/google-cloud/mono-repo-publish/build/src/bin/mono-repo-publish.js?l=123):29)
    at processTicksAndRejections ([internal/process/task_queues.js:95](https://cs.corp.google.com/piper///depot/google3/internal/process/task_queues.js?l=95):5) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 153,
  stdout: null,
  stderr: null
}
```

**Comment by sofisl** [comment]
I think we solved this at least temporarily for google-cloud-node. We're working with @dansaadati on a fix in nodejs-cloud-rad that's more permanent.
