### ISSUE TITLE
Unable to authenticate using `client_email` and `private_key` credentials object

### ISSUE THREAD

**Issue by Kylar13** [googleapis/google-cloud-node#3824]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Mac OS 12.6
  - Node.js version: v16.18.1
  - npm version: 8.19.2
  - @google-cloud/documentai: 6.1.0
  - google-gax: 3.5.2

#### Steps to reproduce

```
import { DocumentProcessorServiceClient } from "@google-cloud/documentai/build/src/v1";
const client = new DocumentProcessorServiceClient({
    options: {
      credentials: {
        client_email: "***",
        private_key: "***",
      },
      projectId: "***",
      apiEndpoint: "eu-documentai.googleapis.com",
    },
  });
```

Error:

```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:206:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GoogleAuth.getClient (node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:638:17)
    at async GrpcClient._getCredentials (node_modules/google-gax/src/grpc.ts:207:20)
    at async GrpcClient.createStub (node_modules/google-gax/src/grpc.ts:409:19)
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sofisl** [comment]
Hi @Kylar13, I'll dig into this more if you're still having issues, but it seems that at a cursory glance, you can just set your credentials as a top-level object, like:

```
const client = new DocumentProcessorServiceClient({
      credentials: {
        client_email: "***",
        private_key: "***",
      },
      projectId: "***",
      apiEndpoint: "eu-documentai.googleapis.com",
    });
```

**Comment by pearigee** [comment]
We are going to close this issue for now given its age. Please create a new issue if needed.
