### ISSUE TITLE
CreateTransferConfig returning unclear INVALID ARGUMENT error

### ISSUE THREAD

**Issue by huangjeff5** [googleapis/google-cloud-node#4010]
I'm having trouble getting a working Node example of creating a BigQuery data transfer config. My goal is to have a nodeJS script that can create transfer configs based on some input JSON.

I found this example to create a BigQuery transfer config so that I can schedule queries: https://github.com/googleapis/nodejs-bigquery-data-transfer/blob/main/samples/generated/v1/data_transfer_service.create_transfer_config.js

I also looked at https://cloud.google.com/bigquery/docs/scheduling-queries#set_up_scheduled_queries_with_a_service_account for an example of a full valid transfer config object and mirrored it in my NodeJS code.

Here's my code based off of that:

#### Environment details

  - which product (packages/*): @google-cloud/bigquery-data-transfer
  - OS: Apple M1 Pro, 13.2.1 (22D68)
  - Node.js version: 14.20.1
  - npm version: 6.14.17
  - google-cloud-node version: 3.2.1

#### Steps to reproduce

Here's my code:

```
'use strict';

function main() {
  const {DataTransferServiceClient} = require('@google-cloud/bigquery-data-transfer').v1;

  const projectId = "projects/[redacted]";
  const datasetId = "test";
  const tableName = "test"
  const queryString = "SELECT * FROM `[redacted].test.test`";
  const transferConfig = {
    destinationDatasetId: datasetId,
    displayName: "Your Scheduled Query Name",
    dataSourceId: "scheduled_query",
    params: {
        "query": queryString,
        "destination_table_name_template": `${tableName}_{run_time|"%H%M%S"}`,
        "write_disposition": "WRITE_TRUNCATE",
        "partitioning_field": "",
    },
    schedule: "every 24 hours",
  };
  console.log(transferConfig);

  // Instantiates a client
  const datatransferClient = new DataTransferServiceClient({keyFilename: "credentials.json"});

  async function callCreateTransferConfig() {
    // Construct request
    const request = {
      parent: projectId,
      transferConfig,
    };

    // Run request
    const response = await datatransferClient.createTransferConfig(request);
    console.log(response);
  }

  callCreateTransferConfig();
  // [END bigquerydatatransfer_v1_generated_DataTransferService_CreateTransferConfig_async]
}

process.on('unhandledRejection', err => {
  console.error(err.message);
  process.exitCode = 1;
});
main();
```

And this is the error I get:
```
Error: 3 INVALID_ARGUMENT: Parameters:  Missing parameter: query. Config name: 
    at callErrorFromStatus (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /Users/huangjeff/Desktop/bigquery-scheduler/node_modules/@google-cloud/bigquery-data-transfer/build/src/v1/data_transfer_service_client.js:216:29
    at /Users/huangjeff/Desktop/bigquery-scheduler/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at OngoingCallPromise.call (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/Users/huangjeff/Desktop/bigquery-scheduler/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /Users/huangjeff/Desktop/bigquery-scheduler/node_modules/google-gax/build/src/createApiCall.js:84:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 3,
  details: 'Parameters:  Missing parameter: query. Config name: ',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  }
}
```

**Comment by pearigee** [comment]
We are going to close this issue for now given its age. Please open a new issue if you have any issues.
