### ISSUE TITLE
google.cloud.texttospeech.v1.TextToSpeech timeout error

### ISSUE THREAD

**Issue by ShortByte** [googleapis/google-cloud-node#4311]
Hello, 

I have the NodeJS @google-cloud/text-to-speech library in use. Locally I have no problems generating text to audio. But when I build the application as a Docker image and run it on my server, I always get the following error after a long time. NodeJS version is the same.

What is the reason for this?

```
GoogleError: Total timeout of API google.cloud.texttospeech.v1.TextToSpeech exceeded 300000 milliseconds before any response was received.
    at repeat (/data/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
    at Timeout._onTimeout (/data/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 4
}
```

**Comment by Davies-Owen** [comment]
I'm running into a similar problem with the Vision image annotation endpoint: 
```
GoogleError: Total timeout of API google.cloud.vision.v1.ImageAnnotator exceeded 600000 milliseconds before any response was received.
   at repeat (/home/node/project/node_modules/google-gax/build/src/normalCalls/retries.js:66:31)
   at Timeout._onTimeout (/home/node/project/node_modules/google-gax/build/src/normalCalls/retries.js:101:25)
   at listOnTimeout (node:internal/timers:569:17)
   at process.processTimers (node:internal/timers:512:7) {
   code: 4
}
```

**Comment by mjadsmurai** [comment]
Seems to happen on all services:
`Total timeout of API google.cloud.tasks.v2.CloudTasks exceeded 20000 milliseconds before any response was received.`
when calling `listTasksAsync`
