### ISSUE TITLE
Error: 13 INTERNAL: Received RST_STREAM with code 0 when trying to call v1beta1 APIs: prediction_service.predict, endpoint_service.undeploy_model 

### ISSUE THREAD

**Issue by fransiskapw** [googleapis/google-cloud-node#4494]
Hello there

I'm trying to call [Prediction_service.predict](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-aiplatform/samples/generated/v1beta1/prediction_service.predict.js) and [endpoint_service.undeploy_model ](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-aiplatform/samples/generated/v1beta1/endpoint_service.undeploy_model.js)- both in v1beta1 and following the code sample, but got error (see below) instead. 

I was able to call the listEndpoints() as shared on the QuickStart

Any help would be appreaciated!
```
Error: 13 INTERNAL: Received RST_STREAM with code 0
    at callErrorFromStatus (..\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (..\node_modules\@grpc\grpc-js\build\src\client.js:192:76)
    at Object.onReceiveStatus (..\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)
    at Object.onReceiveStatus (..\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at ..\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (..\node_modules\@grpc\grpc-js\build\src\client.js:160:32)
    at ServiceClientImpl.<anonymous> (..\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at ..\node_modules\@google-cloud\aiplatform\build\src\v1\prediction_service_client.js:219:29
    at ..\node_modules\google-gax\build\src\normalCalls\timeout.js:44:16
    at OngoingCallPromise.call (..\node_modules\google-gax\build\src\call.js:67:27)
    at NormalApiCaller.call (..\node_modules\google-gax\build\src\normalCalls\normalApiCaller.js:34:19)
    at ..\node_modules\google-gax\build\src\createApiCall.js:84:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 13,
  details: 'Received RST_STREAM with code 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by alexander-fenster** [comment]
Hi @fransiskapw,

Can you paste your code - especially, the request you are sending? Please feel free to edit all the values, I just wanted to make sure that the structure of the request object is what the backend expects.

**Comment by fransiskapw** [comment]
Hi @alexander-fenster, please find the codes below, I followed the code form the sample
```
const aiplatformV1beta1 = require('@google-cloud/aiplatform').v1beta1;
const projectId = ''; #omitted
const location = ''; #omitted
const endpointId = ''; #omitted
const deployedModelId = ''; #omitted

async function callPredict(instances) {
	// Instantiates a client
	const clientPredict = new aiplatformV1beta1.PredictionServiceClient();
	const endpoint = `projects/${projectId}/locations/${location}/endpoints/${endpointId}`;

	// Construct request
	const request1 = {
		endpoint,
		instances,
	};

	// Run request
	try {
		const response = await clientPredict.predict(request1);
		console.log(response);
	} catch (err) {
		console.log(err);
	}
}

async function callDeployUndeployModel(toDeploy) {
	// Instantiates a client
	const aiplatformClient = new aiplatformV1beta1.EndpointServiceClient();
	const endpoint = `projects/${projectId}/locations/${location}/endpoints/${endpointId}`;

  // Construct request
  const request = {
	endpoint,
	deployedModelId,
  };

	// Run request
	try {
		if (toDeploy) {
			const [operation] = await aiplatformClient.deployModel(request);
			const [response] = await operation.promise();
			console.log(response);
		} else {
			// undeploy model
			const [operation] = await aiplatformClient.undeployModel(request);
			const [response] = await operation.promise();
			console.log(response);
		}
		
	} catch (err) {
		console.log(err);
	}
}

const gcpAIPlatform = {
	callPredict,
	callDeployModel : () => callDeployUndeployModel(true),
	callUndeployModel : () => callDeployUndeployModel(false),
}
module.exports = gcpAIPlatform;
```

**Comment by htanjo** [comment]
I encountered the same error with EndpointServiceClient.
In my case, `apiEndpoint` option solved the issue.

```js
const client = new aiplatform.v1.EndpointServiceClient();
client.listEndpoints({ parent: formattedParent });  // Error!
```
↓
```js
const client = new aiplatform.v1.EndpointServiceClient({
  apiEndpoint: 'us-central1-aiplatform.googleapis.com' 
});
client.listEndpoints({ parent: formattedParent });  // Works!
```

Not sure if your are in the same situation, but I hope it helps.

**Comment by fransiskapw** [comment]
Thanks, adding `apiEndpoint` to `EndpointServiceClient` and `PredictionServiceClient` solved the issue!
