### ISSUE TITLE
 Cannot find module '@google-cloud/tasks/build/protos/protos'

### ISSUE THREAD

**Issue by aphofstede** [googleapis/google-cloud-node#5058]
#### Environment details

  - which product (packages/*): Cloud Tasks
  - OS: macos
  - Node.js version: 21
  - npm version: 8
  - google-cloud-node version: 5.0.0

#### Steps to reproduce

Since v5, in TypeScript, resolve the google.cloud.tasks.v2.ITask interface from the package. 

```
    Cannot find module '@google-cloud/tasks/build/protos/protos' from 'src/services/taskQueue/taskQueue.ts'

    Require stack:
       6 | import { CloudTasksClient } from '@google-cloud/tasks';
    >  7 | import { google } from '@google-cloud/tasks/build/protos/protos';
         | ^
       9 | import ITask = google.cloud.tasks.v2.ITask;
      10 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (src/services/taskQueue/taskQueue.ts:7:1)
```

Seems to resolve fine in the IDE, but during TS compilation /  Jest test run the error appears.

EDIT: Workaround: Use the namespaced type name directly, e.g.
```
    const task: google.cloud.tasks.v2.ITask = {
      httpRequest: {
      ...

**Comment by sofisl** [comment]
Great, was able to reproduce. Submitted https://github.com/googleapis/gapic-generator-typescript/pull/1543 as a fix.

**Comment by sofisl** [comment]
@aphofstede, I've just released 5.1.1 which should contain the fix for this. Could I trouble you to give it a try and see if it works?

**Comment by aphofstede** [comment]
Works. ty

**Comment by sofisl** [comment]
Hm, I'm seeing it in the latest version, that code mentioned above only released the duplicate, see
![Screenshot 2024-12-05 at 4 08 27 PM](https://github.com/user-attachments/assets/7834c48d-8f45-4f88-8478-0a15be9e4f05)
if you're targeting esm, is it possible you need to add the full file path `@google-cloud/tasks/build/protos/protos`?

**Comment by vijayprakashpj** [comment]
@aphofstede I had the same problem and here is how I fixed it by changing the import statement.

```typescript
import { protos } from '@google-cloud/tasks'
```

The types under `google` namespace are now accessible from `protos.google.[...]`.
Hope this helps.
