### ISSUE TITLE
This lib seems to block event loop

### ISSUE THREAD

**Issue by chrisdostert** [googleapis/google-cloud-node#7197]
#### Environment details

  - OS: alpine linux
  - Node.js version: 14
  - `@google-cloud/profiler` version: 4.0.2

#### Steps to reproduce

  1. start an app with [blocked-at](https://www.npmjs.com/package/blocked-at) and @google-cloud profiler wired up
  2. watch logs and you'll see frequent blocking operations logged between 2-8 seconds example:
```shell
Blocked for 7586.2085ms, operation started here: [
  '    at Profiler.collectProfile (/src/backend/node_modules/@google-cloud/profiler/src/profiler.ts:393:25)',
  '    at Profiler.runLoop (/src/backend/node_modules/@google-cloud/profiler/src/profiler.ts:379:36)',
  '    at listOnTimeout (internal/timers.js:551:17)',
  '    at processTimers (internal/timers.js:494:7)'
]
```

**Comment by pearigee** [comment]
This issue is stale (no comment in 2+ years) and is being bulk closed. Please reopen if the issue persists. Thanks.
