### ISSUE TITLE
Cannot run tests with `./docs` directory present

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#7199]
We use `jsdoc` to generate docs for the project.  When you generate docs, then run `npm test`, you get a wild stack trace.

$ npm run docs
$ npm test

Using node.js 11.5.0 on OSX.

```
> nyc mocha  out/test/test-*.js

/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/convert-source-map/index.js:40
    throw new Error('An error occurred while trying to read the map file at ' + filepath + '\n' + e);
    ^

Error: An error occurred while trying to read the map file at /Users/beckwith/Code/cloud-profiler-nodejs/docs/scripts/jquery.min.map
Error: ENOENT: no such file or directory, open '/Users/beckwith/Code/cloud-profiler-nodejs/docs/scripts/jquery.min.map'
    at readFromFileMap (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/convert-source-map/index.js:40:11)
    at new Converter (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/convert-source-map/index.js:47:32)
    at Object.exports.fromMapFileComment (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/convert-source-map/index.js:110:10)
    at Object.exports.fromMapFileSource (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/convert-source-map/index.js:122:22)
    at SourceMaps.extractAndRegister (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/nyc/lib/source-maps.js:20:73)
    at /Users/beckwith/Code/cloud-profiler-nodejs/node_modules/nyc/index.js:253:56
    at transform (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/caching-transform/index.js:45:10)
    at /Users/beckwith/Code/cloud-profiler-nodejs/node_modules/caching-transform/index.js:54:11
    at NYC._transform (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/nyc/index.js:228:12)
    at NYC._maybeInstrumentSource (/Users/beckwith/Code/cloud-profiler-nodejs/node_modules/nyc/index.js:236:17)
```

**Comment by pearigee** [comment]
This issue is stale (no comment in 2+ years) and is being bulk closed. Please reopen if the issue persists. Thanks.
