### ISSUE TITLE
Error getting documents:  Error: 9 FAILED_PRECONDITION when using collectionGroup

### ISSUE THREAD

**Issue by dumitruPuggle** [googleapis/google-cloud-node#7466]
#### Environment details

  - OS: 13.2.1 (22D68)
  - Node.js version: v18.15.0
  - npm version: v9.5.0
  - `@google-cloud/firestore` version: I was told to come to this repo to get the responses quickly, although I'm using firestore-admin 11.9.0

#### Steps to reproduce

  1. Use any collectionGroup and call get function 
  ``` ts
   db.collectionGroup("textTemplates")
    .where("id", "==", templateId)
    .get()
  ```
  3. You'll receive an error:
  ``` bash
Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
>  Error getting documents:  Error: 9 FAILED_PRECONDITION: 
>      at callErrorFromStatus (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
>      at Object.onReceiveStatus (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/client.js:357:73)
>      at Object.onReceiveStatus (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
>      at /Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
>      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
>  for call at
>      at ServiceClientImpl.makeServerStreamRequest (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/client.js:340:32)
>      at ServiceClientImpl.<anonymous> (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
>      at /Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:227:29
>      at /Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
>      at /Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
>      at Object.request (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
>      at makeRequest (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/retry-request/index.js:141:28)
>      at retryRequest (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/retry-request/index.js:109:5)
>      at StreamProxy.setStream (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)
>      at StreamingApiCaller.call (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16)
>  Caused by: Error
>      at Query._get (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
>      at Query.get (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
>      at startTextSequencesHandler (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/lib/functions/callable/start-text-sequences.js:25:10)
>      at fixedLen (/Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/firebase-functions/lib/v2/providers/https.js:118:31)
>      at /Users/dumitrucucu/Desktop/VRSEN/admagic-ai/back/functions/node_modules/firebase-functions/lib/common/providers/https.js:467:32
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async runFunction (/Users/dumitrucucu/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)
>      at async runHTTPS (/Users/dumitrucucu/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:531:5)
>      at async /Users/dumitrucucu/.nvm/versions/node/v18.15.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:693:21 {
>    code: 9,
>    details: '',
>    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
>  }
```

I created the necessary indexes on Firestore Console:
<img width="1033" alt="Screenshot 2023-07-25 at 17 42 50" src="https://github.com/googleapis/google-cloud-node/assets/46863241/aaec2fdc-13fe-4130-bdfb-e4edd8539555">

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by leonardopn** [comment]
My firebase-admin: ^11.10.1

Same problem running this code snippet in a deployed code:

```typescript
static async getAllByIdProduct(id: string) {
	const query = await firestore
		.collectionGroup("modelos")
		.where("idsDeProduto", "array-contains", id)
		.get();

	return query.docs.map(doc => ({
		data: doc.data() as RoteiroModelDTO,
		ref: doc.ref as DocumentReference<RoteiroModelDTO>,
	}));
}
```
Error in GCP:

![image](https://github.com/googleapis/google-cloud-node/assets/39427966/5efb017d-dd2c-4ccd-bb74-30205af3cc48)

It really seems that the link to create the indexes should come, but it's just showing a generic error

**Comment by dumitruPuggle** [comment]
Hi guys

Was this issue resolved? I'm asking because I'm sill getting this error in production. 

<img width="1594" alt="Screenshot 2023-09-19 at 23 02 31" src="https://github.com/googleapis/google-cloud-node/assets/46863241/5d6c64f4-412f-42bb-845a-de64da9db89c">

**Comment by dumitruPuggle** [comment]
Hey guys,

I found an alternative solution to fix this problem.
Here are the steps:
<img width="940" alt="Screenshot 2023-11-05 at 00 27 30" src="https://github.com/googleapis/google-cloud-node/assets/46863241/8ddc8259-e565-4c34-8b9c-ef6eebe2392c">

1. Go to Firestore

2. Click on Query builder tab
3. Replicate the same query through UI:
<img width="1353" alt="Screenshot 2023-11-05 at 00 28 10" src="https://github.com/googleapis/google-cloud-node/assets/46863241/e4a6af76-df8d-4e3e-86a7-88d005efadf6">

That's it. You get the index link in console.

**Comment by leblancmeneses** [comment]
I've been a Firebase user since 2016. This error did not include the link to create the missing index, making it difficult to manually create this collection group index.

![image](https://github.com/googleapis/google-cloud-node/assets/730804/57210d0b-012a-4dbe-9e1b-fa3701673412)

This worked in the emulator, but in production, it failed because the emulator doesn't use indexes. Not having the link resulted in an unnecessary time sink.  I'm lucky to have known what query I added and prior projects I could take the collection group index out to modify for this new application I was working on.

```
{
  "indexes": [],
  "fieldOverrides": [
    {
      "collectionGroup": "shortredirectlink_shortlink_campaigns_cg",
      "fieldPath": "short_code",
      "indexes": [
        {
          "order": "ASCENDING",
          "queryScope": "COLLECTION"
        },
        {
          "order": "DESCENDING",
          "queryScope": "COLLECTION"
        },
        {
          "arrayConfig": "CONTAINS",
          "queryScope": "COLLECTION"
        },
        {
          "order": "ASCENDING",
          "queryScope": "COLLECTION_GROUP"
        }
      ]
    }]
}

```

**Comment by silasljennings** [comment]
I want to add to this thread. The solution I found for this was as simple (not so simple if you don't know) as going to the console query builder and executing the query I wanted to execute. In terms of running it on the collectionGroup, it will not execute but will give you the link to setup the indexes you are missing. 

<img width="1291" alt="Screenshot 2024-12-19 at 10 31 57 PM" src="https://github.com/user-attachments/assets/cf0a055c-6e1b-4f87-9d58-e0387a7e8604" />

**Comment by arnotixe** [comment]
same here, adding orderBy and adding/removing try/catch does not yield the famous query creation link. Maybe the creation link is built only for composite indices @google? 

My situation: wanted to collectionGroup('invoice').where('nextRetry', '>', 0)… when I have that db structure:
```
company/{companyId}/invoice
```

Fix ended up being going to the Firebase Console, Firestore → Indexes → **Single field** → Add excemption for collectionId "invoice", field path "nextRetry"

Tried a couple variations of adding a **composite** index involving my nextRetry field, but that did NOT work (and I got "this index is unnecessary" messages when selecting only 1 field).

After some index building time it now collectionGroup()s 🥳 
<img width="274" height="133" alt="Image" src="https://github.com/user-attachments/assets/0cdfa03e-66fc-4178-9d59-bfd792a52ce3" />

**Comment by perret123** [comment]
> This problem sometimes occurs in NodeJS 18 and 20, but not 16 from our observation.
> 
> For Cloud Functions and Firebase Functions, reducing the engine to NodeJS version 16 removes the problem.

We are with Node 22 now, and I just want to let the Google-Team know, that it is really a pain to create these indexes manually. I also have to say I am not a big spender yet, but still it would be great for the developer and especially the deployment experience to have this working for composite indexes also. Thank you :-)

**Comment by wooliet** [comment]
In the past, I used the GCP console firestore query builder to generate the helper URL. 

I cannot get that to work this time because I am targeting a `collectionGroup`, and the "Collection group" input is a dropdown selection that does _not_ include the needed collection name (the possible selections are sorted alpha and limited in number). 

Any workaround to this limitation?

**Comment by dlarocque** [comment]
Hey everyone- sorry for the long delay on this.   
Tom's observation about Node 16 vs 18 helped isolate the issue.

**Issue:**
1. The Firestore backend formats the composite index error message with a trailing space.  
2. Node 18 updated its internal HTTP/2 parser ([`llhttp`](https://github.com/nodejs/llhttp)) to strictly enforce [RFC 9113 \- field name validity](https://www.rfc-editor.org/rfc/rfc9113.html#name-field-validity), which rejects headers and trailers ending in unescaped whitespace.   
3. Because gRPC sends error messages as HTTP/2 trailers, Node 18 drops the error message text internally before it reaches gRPC or even the SDK.   
4. This results in the blank `FAILED_PRECONDITION` error.

**Fix & Rollout**
I submitted a fix to the Firestore backend to remove the trailing space from this error message template, along with 2 others. The change rolled out to our nightly environment today, and I verified that the index creation links are appearing correctly again in Node 18+.  
It will take a few weeks to roll out to prod if there are no issues/rollbacks. No SDK update is required- the index creation links should just start appearing again once the backend fix is rolled out.

@arnotixe - the single-field exemption error template does not have a trailing space, so it's a different issue. Please open a new issue so we can look into it separately.

I will update this thread when the prod rollout is complete.

**Comment by dlarocque** [comment]
The prod rollout is complete, and I've verified that index creation links are now in error messages. If anyone is still facing issues with this, please open a new issue.
